CREATE TABLE `pdd_orders` (
  `id` varchar(50) NOT NULL,
  `account_id` varchar(50) NOT NULL,
  `order_sn` varchar(50) DEFAULT NULL,
  `goods_id` bigint(20) DEFAULT NULL,
  `goods_name` varchar(100) DEFAULT NULL,
  `goods_thumbnail_url` varchar(255) DEFAULT NULL,
  `goods_quantity` bigint(20) DEFAULT NULL,
  `goods_price` bigint(20) DEFAULT NULL,
  `order_amount` bigint(20) DEFAULT NULL,
  `p_id` varchar(50) DEFAULT NULL,
  `promotion_rate` bigint(20) DEFAULT NULL,
  `promotion_amount` bigint(20) DEFAULT NULL,
  `order_status` int(11) DEFAULT NULL,
  `order_status_desc` varchar(50) DEFAULT NULL,
  `order_create_time` bigint(20) DEFAULT NULL,
  `order_pay_time` bigint(20) DEFAULT NULL,
  `order_group_success_time` bigint(20) DEFAULT NULL,
  `order_verify_time` bigint(20) DEFAULT NULL,
  `order_modify_at` bigint(20) DEFAULT NULL,
  `custom_parameters` varchar(255) DEFAULT NULL,
  `cpa_new` int(11) DEFAULT NULL,
  `type` int(11) DEFAULT NULL,
  `order_settle_time` bigint(20) DEFAULT NULL,
  `auth_duo_id` bigint(20) DEFAULT NULL,
  `batch_no` varchar(255) DEFAULT NULL,
  `order_receive_time` bigint(20) DEFAULT NULL,
  `group_id` bigint(20) DEFAULT NULL,
  `fail_reason` varchar(255) DEFAULT NULL,
  `order_id` varchar(50) NOT NULL,
  `zs_duo_id` bigint(20) DEFAULT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `row_version` bigint(20) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_id` (`order_id`) USING BTREE,
  KEY `idx_account_id` (`account_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;